### ISSUE TITLE
flask db migrate sqlalchemy.exc.NoReferencedTableError exception

### ISSUE THREAD

**Issue by louking** [louking/webmodules#26]
related to #18

happens with ca466fc279ee2dadf18d3619c0d027eee7e93fb3
```
(.venv) PS C:\Users\lking\Documents\Lou's Software\projects\webmodules.code-workspace\webmodules> docker exec webmodules-shell-1 flask db migrate -m "add users database, and users oriented tables"
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/cli.py", line 105, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 170, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 229, in revision
    script_directory.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 182, in <module>
    run_migrations_online()
  File "migrations/env.py", line 162, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 205, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 525, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 572, in _run_environment
    compare._populate_migration_script(
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 55, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 89, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "/usr/local/lib/python3.9/site-packages/alembic/util/langhelpers.py", line 267, in go
    fn(*arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 125, in _autogen_for_tables
    [(table.schema, table.name) for table in autogen_context.sorted_tables]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 442, in sorted_tables
    result.extend(m.sorted_tables)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 5353, in sorted_tables
    return ddl.sort_tables(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1264, in sort_tables
    for (t, fkcs) in sort_tables_and_constraints(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1342, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4487, in referred_table
    return self.elements[0].column.table
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 2918, in column
    return self._resolve_column()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 2942, in _resolve_column
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'apps_interests.application_id' could not find table 'application' with which to generate a foreign key to target column 'id'
```

**Comment by louking** [comment]
- tried flask-sqlalchemy 3.0.3 + sqlalchemy 2.0.11 - still happens
- tried flask-sqlalchemy 3.0.3 + sqlalchemy 1.4.47 - still happens
- tried flask-sqlalchemy 2.5.1 + sqlalchemy 1.4.47 - fixes
- tried flask-sqlalchemy 2.5.1 + sqlalchemy 2.0.11 - seems not to be supported

queried flask-sqlalchemy developers
- https://discord.com/channels/531221516914917387/531571912619458591/1101567562535424090

**Comment by louking** [comment]
but see #28
