### ISSUE TITLE
delete interest, MultipleRowsFound exception (latent?)

### ISSUE THREAD

**Issue by louking** [louking/webmodules#44]
```
Message type:       ERROR
Location:           /usr/local/lib/python3.9/site-packages/loutilities/tables.py:754
Module:             tables
Function:           wrapped_f
Time:               2023-05-20 11:15:35,914
User:               ********

Message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/loutilities/tables.py", line 740, in wrapped_f
    self.editor_method_postcommit(request.form)
  File "/app/webmodules/views/userrole/userrole.py", line 40, in editor_method_postcommit
    update_local_tables()
  File "/app/webmodules/model.py", line 75, in update_local_tables
    localtables.update()
  File "/usr/local/lib/python3.9/site-packages/loutilities/user/model.py", line 292, in update
    self._updateuser_byinterest()
  File "/usr/local/lib/python3.9/site-packages/loutilities/user/model.py", line 228, in _updateuser_byinterest
    localuser = self.localusermodel.query.filter_by(user_id=user_id, interest_id=interest_id).one()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1522, in one
    return self._only_one_row(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
```

**Comment by louking** [comment]
this was due to database entry created with interest_id=null, when earlier version of software didn't support interests. When retrieve of interest_id=None was requested, all rows which matched user_id were retrieved, not one.

**Comment by louking** [comment]
but when the interest is actually deleted, this leaves null in the interest_id, so the same behavior will be seen.
